theme = "shades_of_purple"

[editor]
line-number = "relative"
scrolloff = 10

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "position", "file-encoding", "version-control"]

[keys.normal]
a = ["insert_mode", "move_char_right", "collapse_selection"]

A-up = "move_line_up"
A-down = "move_line_down"

A-right = "move_next_word_start"
A-left = "move_prev_word_end"
A-S-right = "extend_next_word_end"
A-S-left = "extend_prev_word_start"
S-right = "extend_char_right"
S-left = "extend_char_left"

[keys.normal.q]
d = "normal_mode"

[keys.insert]
A-up = "move_line_up"
A-down = "move_line_down"

A-right = "move_next_word_start"
A-left = "move_prev_word_end"
A-S-right = "extend_next_word_end"
A-S-left = "extend_prev_word_start"
S-right = "extend_char_right"
S-left = "extend_char_left"

[keys.insert.q]
d = "normal_mode"

[keys.select]
"A-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "select_mode", "extend_to_line_bounds"]
"A-down" = ["extend_to_line_bounds", "delete_selection", "paste_after", "select_mode","extend_to_line_bounds"]
